version: '3.8'

services:
  temperature:
    image: alvarofp/sensor-temperatura
    deploy:
      replicas: 4
    

  occupation:
    image: alvarofp/sensor-ocupacion
    deploy:
      replicas: 6
    
   
  power:
    image: alvarofp/sensor-power
    deploy:
      replicas: 7
    

  cameras:
    image: alvarofp/sensor-camara
    deploy:
      replicas: 3
    
