version: '3.8'

services:
  temperature:
    build:
      ./Temperature
    deploy:
      replicas: 4
    

  occupation:
    build:
        ./Occupancy
    deploy:
      replicas: 6
    
   
  power:
    build:
        ./Power
    deploy:
      replicas: 7
    

  cameras:
    build:
        ./Security
    deploy:
      replicas: 3
    
