version: '3.8'

services:
  temperature:
    image: alvarofp/sensor-temperatura:1.0
    deploy:
      replicas: 4
    

  occupation:
    image: alvarofp/sensor-ocupacion:1.0
    deploy:
      replicas: 6
    
   
  power:
    image: alvarofp/sensor-power:1.0
    deploy:
      replicas: 7
    

  cameras:
    image: alvarofp/sensor-camara:1.0
    deploy:
      replicas: 3
    
