version: '3.8'

services:
  temperature:
    image: alvarofp/sensor-temperatura:4.0
    deploy:
      replicas: 4
    networks:
      - building-network
    

  occupation:
    image: alvarofp/sensor-ocupacion:4.0
    deploy:
      replicas: 6
    networks:
      - building-network
   
  power:
    image: alvarofp/sensor-power:4.0
    deploy:
      replicas: 7
    networks:
      - building-network
    

  cameras:
    image: alvarofp/sensor-camara:4.0
    deploy:
      replicas: 3
    networks:
      - building-network


networks:
  building-network:
    external: True
    