version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
        - "5672:5672"
        - "15672:15672"
    networks:
      - building-network
    environment:
        RABBITMQ_DEFAULT_USER: building
        RABBITMQ_DEFAULT_PASS: password
        RABBITMQ_HEARTBEAT: 18000  # Ajusta el tiempo de latido en segundos
        # RABBITMQ_CONNECTION_TIMEOUT=300000  # Ajusta el tiempo de espera de la conexión en milisegundos
  api-gateway:
    # image: miguelgp13/api-gateway:3.0
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "8080:8080"
    networks:
      - building-network
    environment:
        - RABBITMQ_HOST=rabbitmq
        - RABBITMQ_USERNAME=building
        - RABBITMQ_PASSWORD=password
    depends_on:
      - consumo-service
      - ocupacion-service
      - seguridad-service
      - temperatura-service
      - lector-service

  consumo-service:
    image: miguelgp13/consumo:4.0
    # build:
    #   context: .
    #   dockerfile: Dockerfile.consumo
    volumes:
      - almacen:/data
    networks:
      - building-network
    environment:
        - RABBITMQ_HOST=rabbitmq
        - RABBITMQ_USERNAME=building
        - RABBITMQ_PASSWORD=password
        - RABBITMQ_HEARTBEAT=1800

  ocupacion-service:
    image: miguelgp13/ocupacion:4.0
    # build:
    #   context: .
    #   dockerfile: Dockerfile.ocupacion
    volumes:
      - almacen:/data
    networks:
      - building-network
    environment:
        - RABBITMQ_HOST=rabbitmq
        - RABBITMQ_USERNAME=building
        - RABBITMQ_PASSWORD=password

  seguridad-service:
    image: miguelgp13/seguridad:4.0
    # build:
    #   context: .
    #   dockerfile: Dockerfile.seguridad
    volumes:
      - almacen:/data
    networks:
      - building-network
    environment:
        - RABBITMQ_HOST=rabbitmq
        - RABBITMQ_USERNAME=building
        - RABBITMQ_PASSWORD=password

  temperatura-service:
    image: miguelgp13/temperatura:4.0
    # build:
    #   context: .
    #   dockerfile: Dockerfile.temperatura
    volumes:
      - almacen:/data
    networks:
      - building-network
    environment:
        - RABBITMQ_HOST=rabbitmq
        - RABBITMQ_USERNAME=building
        - RABBITMQ_PASSWORD=password

  lector-service:
    image: miguelgp13/lector:3.0
    # build:
    #   context: .
    #   dockerfile: Dockerfile.lector

    volumes:
      - almacen:/data
    networks:
      - building-network

volumes:
  almacen:

networks:
  building-network:
    external: True
    