FROM python:3.12-slim
WORKDIR /app    
COPY ./temperatura.py ./temperatura.py
COPY ./requirements_saver.txt ./requirements.txt
RUN pip install -r requirements.txt
CMD ["python", "-u", "temperatura.py"]
